from .roles import RolesTest
from .terms_of_service import TermsOfServiceTest
from .administrators import AdministratorsTest
from .users import UsersTest
from .user_profiles import UserProfilesTest
from .auth_token import AuthTokenTest
from .logins import LoginsTest
from .app_keys import AppKeysTest
from .password import PasswordTest
from .user_account import UserAccountTest
from .countries import CountriesTest
from .regions import RegionsTest
from .password_resets import PasswordResetsTest
from .notifications import NotificationsTest
