version: 2

jobs:
  build:

    docker:
      - image: circleci/python:3.9.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
#           PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://api_admin:passpass@localhost:5432/api_db_test
          SECRET_KEY: SrJMTtdN7vu9NBBLgzNYRczC3UaWbUYuSwzD7CDduRfNjSPPKQZYzpjQFP4fKD3C
          AUTH_SECRET_KEY: XHmhmQzSqudjUBpuYT7CXUCnsJC4j274T84E7Hm7MYHccY8Gyfeg4apzPKxbb76N
          AUTH_TOKEN_EXPIRATION: 14400
          AUTH_HASH_ROUNDS: 4
          CRYPT_SYM_SECRET_KEY: VEsuvPZ2W5M8Hb8s7cddMyAMB3g9LPf8VmC4hFmJWckG5htZfgybREBeDa2WaUDs
          CRYPT_DIGEST_SALT: mTqjD2YZKU4SXwT7uADbA5bndcc2meEz9PWgX56acdZUZpKn9X82SaJ67F8x8XAK
          LOGGING_LEVEL: INFO
          PIPENV_PIPFILE: application/Pipfile

    steps:
      - checkout
#       - run: sudo chown -R circleci:circleci /usr/local/bin
#       - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
 
